/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConversationCreate,
  ConversationRead,
  CursorPageConversationRead,
  HTTPValidationError,
} from '../models/index';
import {
    ConversationCreateFromJSON,
    ConversationCreateToJSON,
    ConversationReadFromJSON,
    ConversationReadToJSON,
    CursorPageConversationReadFromJSON,
    CursorPageConversationReadToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateConversationApiV1ConversationsPostRequest {
    conversationCreate: ConversationCreate;
}

export interface DeleteConversationApiV1ConversationsConversationIdDeleteRequest {
    conversationId: string;
}

export interface GetConversationApiV1ConversationsConversationIdGetRequest {
    conversationId: string;
}

export interface ListConversationsApiV1ConversationsGetRequest {
    cursor?: string | null;
    size?: number;
}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createConversationApiV1ConversationsPost without sending the request
     */
    async createConversationApiV1ConversationsPostRequestOpts(requestParameters: CreateConversationApiV1ConversationsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationCreate'] == null) {
            throw new runtime.RequiredError(
                'conversationCreate',
                'Required parameter "conversationCreate" was null or undefined when calling createConversationApiV1ConversationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/conversations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationCreateToJSON(requestParameters['conversationCreate']),
        };
    }

    /**
     * Create Conversation
     */
    async createConversationApiV1ConversationsPostRaw(requestParameters: CreateConversationApiV1ConversationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationRead>> {
        const requestOptions = await this.createConversationApiV1ConversationsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationReadFromJSON(jsonValue));
    }

    /**
     * Create Conversation
     */
    async createConversationApiV1ConversationsPost(requestParameters: CreateConversationApiV1ConversationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationRead> {
        const response = await this.createConversationApiV1ConversationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteConversationApiV1ConversationsConversationIdDelete without sending the request
     */
    async deleteConversationApiV1ConversationsConversationIdDeleteRequestOpts(requestParameters: DeleteConversationApiV1ConversationsConversationIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling deleteConversationApiV1ConversationsConversationIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/conversations/{conversation_id}`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Conversation
     */
    async deleteConversationApiV1ConversationsConversationIdDeleteRaw(requestParameters: DeleteConversationApiV1ConversationsConversationIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteConversationApiV1ConversationsConversationIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Conversation
     */
    async deleteConversationApiV1ConversationsConversationIdDelete(requestParameters: DeleteConversationApiV1ConversationsConversationIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConversationApiV1ConversationsConversationIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConversationApiV1ConversationsConversationIdGet without sending the request
     */
    async getConversationApiV1ConversationsConversationIdGetRequestOpts(requestParameters: GetConversationApiV1ConversationsConversationIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversationApiV1ConversationsConversationIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/conversations/{conversation_id}`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Conversation
     */
    async getConversationApiV1ConversationsConversationIdGetRaw(requestParameters: GetConversationApiV1ConversationsConversationIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationRead>> {
        const requestOptions = await this.getConversationApiV1ConversationsConversationIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationReadFromJSON(jsonValue));
    }

    /**
     * Get Conversation
     */
    async getConversationApiV1ConversationsConversationIdGet(requestParameters: GetConversationApiV1ConversationsConversationIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationRead> {
        const response = await this.getConversationApiV1ConversationsConversationIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversationsApiV1ConversationsGet without sending the request
     */
    async listConversationsApiV1ConversationsGetRequestOpts(requestParameters: ListConversationsApiV1ConversationsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/conversations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Conversations
     */
    async listConversationsApiV1ConversationsGetRaw(requestParameters: ListConversationsApiV1ConversationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CursorPageConversationRead>> {
        const requestOptions = await this.listConversationsApiV1ConversationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CursorPageConversationReadFromJSON(jsonValue));
    }

    /**
     * List Conversations
     */
    async listConversationsApiV1ConversationsGet(requestParameters: ListConversationsApiV1ConversationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CursorPageConversationRead> {
        const response = await this.listConversationsApiV1ConversationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
