/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MessageRead,
  PaginatedMessages,
  SendMessageRequest,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageReadFromJSON,
    MessageReadToJSON,
    PaginatedMessagesFromJSON,
    PaginatedMessagesToJSON,
    SendMessageRequestFromJSON,
    SendMessageRequestToJSON,
} from '../models/index';

export interface GetMessagesApiV1ConversationsConversationIdMessagesGetRequest {
    conversationId: string;
    cursor?: string | null;
    limit?: number;
}

export interface MarkAsReadApiV1MessagesMessageIdReadPatchRequest {
    messageId: string;
}

export interface SendMessageApiV1ConversationsConversationIdMessagesPostRequest {
    conversationId: string;
    sendMessageRequest: SendMessageRequest;
}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMessagesApiV1ConversationsConversationIdMessagesGet without sending the request
     */
    async getMessagesApiV1ConversationsConversationIdMessagesGetRequestOpts(requestParameters: GetMessagesApiV1ConversationsConversationIdMessagesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getMessagesApiV1ConversationsConversationIdMessagesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/conversations/{conversation_id}/messages`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Messages
     */
    async getMessagesApiV1ConversationsConversationIdMessagesGetRaw(requestParameters: GetMessagesApiV1ConversationsConversationIdMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedMessages>> {
        const requestOptions = await this.getMessagesApiV1ConversationsConversationIdMessagesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedMessagesFromJSON(jsonValue));
    }

    /**
     * Get Messages
     */
    async getMessagesApiV1ConversationsConversationIdMessagesGet(requestParameters: GetMessagesApiV1ConversationsConversationIdMessagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedMessages> {
        const response = await this.getMessagesApiV1ConversationsConversationIdMessagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markAsReadApiV1MessagesMessageIdReadPatch without sending the request
     */
    async markAsReadApiV1MessagesMessageIdReadPatchRequestOpts(requestParameters: MarkAsReadApiV1MessagesMessageIdReadPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling markAsReadApiV1MessagesMessageIdReadPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/messages/{message_id}/read`;
        urlPath = urlPath.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark As Read
     */
    async markAsReadApiV1MessagesMessageIdReadPatchRaw(requestParameters: MarkAsReadApiV1MessagesMessageIdReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.markAsReadApiV1MessagesMessageIdReadPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Mark As Read
     */
    async markAsReadApiV1MessagesMessageIdReadPatch(requestParameters: MarkAsReadApiV1MessagesMessageIdReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.markAsReadApiV1MessagesMessageIdReadPatchRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for sendMessageApiV1ConversationsConversationIdMessagesPost without sending the request
     */
    async sendMessageApiV1ConversationsConversationIdMessagesPostRequestOpts(requestParameters: SendMessageApiV1ConversationsConversationIdMessagesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling sendMessageApiV1ConversationsConversationIdMessagesPost().'
            );
        }

        if (requestParameters['sendMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'sendMessageRequest',
                'Required parameter "sendMessageRequest" was null or undefined when calling sendMessageApiV1ConversationsConversationIdMessagesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/conversations/{conversation_id}/messages`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendMessageRequestToJSON(requestParameters['sendMessageRequest']),
        };
    }

    /**
     * Send Message
     */
    async sendMessageApiV1ConversationsConversationIdMessagesPostRaw(requestParameters: SendMessageApiV1ConversationsConversationIdMessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageRead>> {
        const requestOptions = await this.sendMessageApiV1ConversationsConversationIdMessagesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageReadFromJSON(jsonValue));
    }

    /**
     * Send Message
     */
    async sendMessageApiV1ConversationsConversationIdMessagesPost(requestParameters: SendMessageApiV1ConversationsConversationIdMessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageRead> {
        const response = await this.sendMessageApiV1ConversationsConversationIdMessagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
