/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContactCreate,
  ContactRead,
  CursorPageContactRead,
  HTTPValidationError,
  UserRead,
  UserUpdate,
} from '../models/index';
import {
    ContactCreateFromJSON,
    ContactCreateToJSON,
    ContactReadFromJSON,
    ContactReadToJSON,
    CursorPageContactReadFromJSON,
    CursorPageContactReadToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UserReadFromJSON,
    UserReadToJSON,
    UserUpdateFromJSON,
    UserUpdateToJSON,
} from '../models/index';

export interface AddContactApiV1UsersContactsPostRequest {
    contactCreate: ContactCreate;
}

export interface GetContactApiV1UsersContactsContactUserIdGetRequest {
    contactUserId: string;
}

export interface ListContactsApiV1UsersContactsGetRequest {
    q?: string | null;
    cursor?: string | null;
    size?: number;
}

export interface RemoveContactApiV1UsersContactsContactUserIdDeleteRequest {
    contactUserId: string;
}

export interface UpdateMeApiV1UsersMePatchRequest {
    userUpdate: UserUpdate;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for addContactApiV1UsersContactsPost without sending the request
     */
    async addContactApiV1UsersContactsPostRequestOpts(requestParameters: AddContactApiV1UsersContactsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactCreate'] == null) {
            throw new runtime.RequiredError(
                'contactCreate',
                'Required parameter "contactCreate" was null or undefined when calling addContactApiV1UsersContactsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/contacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContactCreateToJSON(requestParameters['contactCreate']),
        };
    }

    /**
     * Add Contact
     */
    async addContactApiV1UsersContactsPostRaw(requestParameters: AddContactApiV1UsersContactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactRead>> {
        const requestOptions = await this.addContactApiV1UsersContactsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactReadFromJSON(jsonValue));
    }

    /**
     * Add Contact
     */
    async addContactApiV1UsersContactsPost(requestParameters: AddContactApiV1UsersContactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactRead> {
        const response = await this.addContactApiV1UsersContactsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getContactApiV1UsersContactsContactUserIdGet without sending the request
     */
    async getContactApiV1UsersContactsContactUserIdGetRequestOpts(requestParameters: GetContactApiV1UsersContactsContactUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactUserId'] == null) {
            throw new runtime.RequiredError(
                'contactUserId',
                'Required parameter "contactUserId" was null or undefined when calling getContactApiV1UsersContactsContactUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/contacts/{contact_user_id}`;
        urlPath = urlPath.replace(`{${"contact_user_id"}}`, encodeURIComponent(String(requestParameters['contactUserId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Contact
     */
    async getContactApiV1UsersContactsContactUserIdGetRaw(requestParameters: GetContactApiV1UsersContactsContactUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactRead>> {
        const requestOptions = await this.getContactApiV1UsersContactsContactUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactReadFromJSON(jsonValue));
    }

    /**
     * Get Contact
     */
    async getContactApiV1UsersContactsContactUserIdGet(requestParameters: GetContactApiV1UsersContactsContactUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactRead> {
        const response = await this.getContactApiV1UsersContactsContactUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMeApiV1UsersMeGet without sending the request
     */
    async getMeApiV1UsersMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Me
     */
    async getMeApiV1UsersMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        const requestOptions = await this.getMeApiV1UsersMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Get Me
     */
    async getMeApiV1UsersMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.getMeApiV1UsersMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContactsApiV1UsersContactsGet without sending the request
     */
    async listContactsApiV1UsersContactsGetRequestOpts(requestParameters: ListContactsApiV1UsersContactsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/contacts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Contacts
     */
    async listContactsApiV1UsersContactsGetRaw(requestParameters: ListContactsApiV1UsersContactsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CursorPageContactRead>> {
        const requestOptions = await this.listContactsApiV1UsersContactsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CursorPageContactReadFromJSON(jsonValue));
    }

    /**
     * List Contacts
     */
    async listContactsApiV1UsersContactsGet(requestParameters: ListContactsApiV1UsersContactsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CursorPageContactRead> {
        const response = await this.listContactsApiV1UsersContactsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeContactApiV1UsersContactsContactUserIdDelete without sending the request
     */
    async removeContactApiV1UsersContactsContactUserIdDeleteRequestOpts(requestParameters: RemoveContactApiV1UsersContactsContactUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contactUserId'] == null) {
            throw new runtime.RequiredError(
                'contactUserId',
                'Required parameter "contactUserId" was null or undefined when calling removeContactApiV1UsersContactsContactUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/contacts/{contact_user_id}`;
        urlPath = urlPath.replace(`{${"contact_user_id"}}`, encodeURIComponent(String(requestParameters['contactUserId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove Contact
     */
    async removeContactApiV1UsersContactsContactUserIdDeleteRaw(requestParameters: RemoveContactApiV1UsersContactsContactUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeContactApiV1UsersContactsContactUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove Contact
     */
    async removeContactApiV1UsersContactsContactUserIdDelete(requestParameters: RemoveContactApiV1UsersContactsContactUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeContactApiV1UsersContactsContactUserIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateMeApiV1UsersMePatch without sending the request
     */
    async updateMeApiV1UsersMePatchRequestOpts(requestParameters: UpdateMeApiV1UsersMePatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userUpdate'] == null) {
            throw new runtime.RequiredError(
                'userUpdate',
                'Required parameter "userUpdate" was null or undefined when calling updateMeApiV1UsersMePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/me`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateToJSON(requestParameters['userUpdate']),
        };
    }

    /**
     * Update Me
     */
    async updateMeApiV1UsersMePatchRaw(requestParameters: UpdateMeApiV1UsersMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        const requestOptions = await this.updateMeApiV1UsersMePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Update Me
     */
    async updateMeApiV1UsersMePatch(requestParameters: UpdateMeApiV1UsersMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.updateMeApiV1UsersMePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
