/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactCreate
 */
export interface ContactCreate {
    /**
     * 
     * @type {string}
     * @memberof ContactCreate
     */
    phone: string;
}

/**
 * Check if a given object implements the ContactCreate interface.
 */
export function instanceOfContactCreate(value: object): value is ContactCreate {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function ContactCreateFromJSON(json: any): ContactCreate {
    return ContactCreateFromJSONTyped(json, false);
}

export function ContactCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function ContactCreateToJSON(json: any): ContactCreate {
    return ContactCreateToJSONTyped(json, false);
}

export function ContactCreateToJSONTyped(value?: ContactCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

