/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LastMessageRead } from './LastMessageRead';
import {
    LastMessageReadFromJSON,
    LastMessageReadFromJSONTyped,
    LastMessageReadToJSON,
    LastMessageReadToJSONTyped,
} from './LastMessageRead';
import type { ConversationType } from './ConversationType';
import {
    ConversationTypeFromJSON,
    ConversationTypeFromJSONTyped,
    ConversationTypeToJSON,
    ConversationTypeToJSONTyped,
} from './ConversationType';
import type { ParticipantRead } from './ParticipantRead';
import {
    ParticipantReadFromJSON,
    ParticipantReadFromJSONTyped,
    ParticipantReadToJSON,
    ParticipantReadToJSONTyped,
} from './ParticipantRead';

/**
 * 
 * @export
 * @interface ConversationRead
 */
export interface ConversationRead {
    /**
     * 
     * @type {string}
     * @memberof ConversationRead
     */
    id: string;
    /**
     * 
     * @type {ConversationType}
     * @memberof ConversationRead
     */
    type: ConversationType;
    /**
     * 
     * @type {string}
     * @memberof ConversationRead
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationRead
     */
    avatar: string | null;
    /**
     * 
     * @type {Array<ParticipantRead>}
     * @memberof ConversationRead
     */
    participants: Array<ParticipantRead>;
    /**
     * 
     * @type {LastMessageRead}
     * @memberof ConversationRead
     */
    lastMessage: LastMessageRead | null;
    /**
     * 
     * @type {number}
     * @memberof ConversationRead
     */
    unreadCount: number;
    /**
     * 
     * @type {Date}
     * @memberof ConversationRead
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConversationRead
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ConversationRead interface.
 */
export function instanceOfConversationRead(value: object): value is ConversationRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    if (!('lastMessage' in value) || value['lastMessage'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ConversationReadFromJSON(json: any): ConversationRead {
    return ConversationReadFromJSONTyped(json, false);
}

export function ConversationReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': ConversationTypeFromJSON(json['type']),
        'name': json['name'],
        'avatar': json['avatar'],
        'participants': ((json['participants'] as Array<any>).map(ParticipantReadFromJSON)),
        'lastMessage': LastMessageReadFromJSON(json['last_message']),
        'unreadCount': json['unread_count'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ConversationReadToJSON(json: any): ConversationRead {
    return ConversationReadToJSONTyped(json, false);
}

export function ConversationReadToJSONTyped(value?: ConversationRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': ConversationTypeToJSON(value['type']),
        'name': value['name'],
        'avatar': value['avatar'],
        'participants': ((value['participants'] as Array<any>).map(ParticipantReadToJSON)),
        'last_message': LastMessageReadToJSON(value['lastMessage']),
        'unread_count': value['unreadCount'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

