/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConversationType {
    Individual = 'individual',
    Group = 'group',
    UnknownDefaultOpenApi = '11184809'
}


export function instanceOfConversationType(value: any): boolean {
    for (const key in ConversationType) {
        if (Object.prototype.hasOwnProperty.call(ConversationType, key)) {
            if (ConversationType[key as keyof typeof ConversationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConversationTypeFromJSON(json: any): ConversationType {
    return ConversationTypeFromJSONTyped(json, false);
}

export function ConversationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationType {
    return json as ConversationType;
}

export function ConversationTypeToJSON(value?: ConversationType | null): any {
    return value as any;
}

export function ConversationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ConversationType {
    return value as ConversationType;
}

