/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationType } from './ConversationType';
import {
    ConversationTypeFromJSON,
    ConversationTypeFromJSONTyped,
    ConversationTypeToJSON,
    ConversationTypeToJSONTyped,
} from './ConversationType';

/**
 * 
 * @export
 * @interface ConversationCreate
 */
export interface ConversationCreate {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConversationCreate
     */
    participantIds: Array<string>;
    /**
     * 
     * @type {ConversationType}
     * @memberof ConversationCreate
     */
    type: ConversationType;
    /**
     * 
     * @type {string}
     * @memberof ConversationCreate
     */
    name?: string | null;
}



/**
 * Check if a given object implements the ConversationCreate interface.
 */
export function instanceOfConversationCreate(value: object): value is ConversationCreate {
    if (!('participantIds' in value) || value['participantIds'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ConversationCreateFromJSON(json: any): ConversationCreate {
    return ConversationCreateFromJSONTyped(json, false);
}

export function ConversationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'participantIds': json['participant_ids'],
        'type': ConversationTypeFromJSON(json['type']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ConversationCreateToJSON(json: any): ConversationCreate {
    return ConversationCreateToJSONTyped(json, false);
}

export function ConversationCreateToJSONTyped(value?: ConversationCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participant_ids': value['participantIds'],
        'type': ConversationTypeToJSON(value['type']),
        'name': value['name'],
    };
}

