/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactRead } from './ContactRead';
import {
    ContactReadFromJSON,
    ContactReadFromJSONTyped,
    ContactReadToJSON,
    ContactReadToJSONTyped,
} from './ContactRead';

/**
 * 
 * @export
 * @interface CursorPageContactRead
 */
export interface CursorPageContactRead {
    /**
     * 
     * @type {Array<ContactRead>}
     * @memberof CursorPageContactRead
     */
    items: Array<ContactRead>;
    /**
     * 
     * @type {number}
     * @memberof CursorPageContactRead
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof CursorPageContactRead
     */
    currentPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CursorPageContactRead
     */
    currentPageBackwards?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CursorPageContactRead
     */
    previousPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CursorPageContactRead
     */
    nextPage?: string | null;
}

/**
 * Check if a given object implements the CursorPageContactRead interface.
 */
export function instanceOfCursorPageContactRead(value: object): value is CursorPageContactRead {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function CursorPageContactReadFromJSON(json: any): CursorPageContactRead {
    return CursorPageContactReadFromJSONTyped(json, false);
}

export function CursorPageContactReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageContactRead {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ContactReadFromJSON)),
        'total': json['total'],
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'currentPageBackwards': json['current_page_backwards'] == null ? undefined : json['current_page_backwards'],
        'previousPage': json['previous_page'] == null ? undefined : json['previous_page'],
        'nextPage': json['next_page'] == null ? undefined : json['next_page'],
    };
}

export function CursorPageContactReadToJSON(json: any): CursorPageContactRead {
    return CursorPageContactReadToJSONTyped(json, false);
}

export function CursorPageContactReadToJSONTyped(value?: CursorPageContactRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ContactReadToJSON)),
        'total': value['total'],
        'current_page': value['currentPage'],
        'current_page_backwards': value['currentPageBackwards'],
        'previous_page': value['previousPage'],
        'next_page': value['nextPage'],
    };
}

