/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationRead } from './ConversationRead';
import {
    ConversationReadFromJSON,
    ConversationReadFromJSONTyped,
    ConversationReadToJSON,
    ConversationReadToJSONTyped,
} from './ConversationRead';

/**
 * 
 * @export
 * @interface CursorPageConversationRead
 */
export interface CursorPageConversationRead {
    /**
     * 
     * @type {Array<ConversationRead>}
     * @memberof CursorPageConversationRead
     */
    items: Array<ConversationRead>;
    /**
     * 
     * @type {number}
     * @memberof CursorPageConversationRead
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof CursorPageConversationRead
     */
    currentPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CursorPageConversationRead
     */
    currentPageBackwards?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CursorPageConversationRead
     */
    previousPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CursorPageConversationRead
     */
    nextPage?: string | null;
}

/**
 * Check if a given object implements the CursorPageConversationRead interface.
 */
export function instanceOfCursorPageConversationRead(value: object): value is CursorPageConversationRead {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function CursorPageConversationReadFromJSON(json: any): CursorPageConversationRead {
    return CursorPageConversationReadFromJSONTyped(json, false);
}

export function CursorPageConversationReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageConversationRead {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ConversationReadFromJSON)),
        'total': json['total'],
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'currentPageBackwards': json['current_page_backwards'] == null ? undefined : json['current_page_backwards'],
        'previousPage': json['previous_page'] == null ? undefined : json['previous_page'],
        'nextPage': json['next_page'] == null ? undefined : json['next_page'],
    };
}

export function CursorPageConversationReadToJSON(json: any): CursorPageConversationRead {
    return CursorPageConversationReadToJSONTyped(json, false);
}

export function CursorPageConversationReadToJSONTyped(value?: CursorPageConversationRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ConversationReadToJSON)),
        'total': value['total'],
        'current_page': value['currentPage'],
        'current_page_backwards': value['currentPageBackwards'],
        'previous_page': value['previousPage'],
        'next_page': value['nextPage'],
    };
}

