/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageStatus } from './MessageStatus';
import {
    MessageStatusFromJSON,
    MessageStatusFromJSONTyped,
    MessageStatusToJSON,
    MessageStatusToJSONTyped,
} from './MessageStatus';
import type { MessageType } from './MessageType';
import {
    MessageTypeFromJSON,
    MessageTypeFromJSONTyped,
    MessageTypeToJSON,
    MessageTypeToJSONTyped,
} from './MessageType';

/**
 * 
 * @export
 * @interface LastMessageRead
 */
export interface LastMessageRead {
    /**
     * 
     * @type {string}
     * @memberof LastMessageRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LastMessageRead
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof LastMessageRead
     */
    senderId: string;
    /**
     * 
     * @type {MessageType}
     * @memberof LastMessageRead
     */
    messageType: MessageType;
    /**
     * 
     * @type {string}
     * @memberof LastMessageRead
     */
    content: string;
    /**
     * 
     * @type {MessageStatus}
     * @memberof LastMessageRead
     */
    status: MessageStatus;
    /**
     * 
     * @type {Date}
     * @memberof LastMessageRead
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the LastMessageRead interface.
 */
export function instanceOfLastMessageRead(value: object): value is LastMessageRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('messageType' in value) || value['messageType'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function LastMessageReadFromJSON(json: any): LastMessageRead {
    return LastMessageReadFromJSONTyped(json, false);
}

export function LastMessageReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastMessageRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'conversationId': json['conversation_id'],
        'senderId': json['sender_id'],
        'messageType': MessageTypeFromJSON(json['message_type']),
        'content': json['content'],
        'status': MessageStatusFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function LastMessageReadToJSON(json: any): LastMessageRead {
    return LastMessageReadToJSONTyped(json, false);
}

export function LastMessageReadToJSONTyped(value?: LastMessageRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'conversation_id': value['conversationId'],
        'sender_id': value['senderId'],
        'message_type': MessageTypeToJSON(value['messageType']),
        'content': value['content'],
        'status': MessageStatusToJSON(value['status']),
        'created_at': value['createdAt'].toISOString(),
    };
}

