/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageStatus } from './MessageStatus';
import {
    MessageStatusFromJSON,
    MessageStatusFromJSONTyped,
    MessageStatusToJSON,
    MessageStatusToJSONTyped,
} from './MessageStatus';
import type { MessageType } from './MessageType';
import {
    MessageTypeFromJSON,
    MessageTypeFromJSONTyped,
    MessageTypeToJSON,
    MessageTypeToJSONTyped,
} from './MessageType';

/**
 * 
 * @export
 * @interface MessageRead
 */
export interface MessageRead {
    /**
     * 
     * @type {string}
     * @memberof MessageRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRead
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRead
     */
    senderId: string;
    /**
     * 
     * @type {MessageType}
     * @memberof MessageRead
     */
    messageType: MessageType;
    /**
     * 
     * @type {string}
     * @memberof MessageRead
     */
    content: string;
    /**
     * 
     * @type {MessageStatus}
     * @memberof MessageRead
     */
    status: MessageStatus;
    /**
     * 
     * @type {string}
     * @memberof MessageRead
     */
    replyToId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MessageRead
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the MessageRead interface.
 */
export function instanceOfMessageRead(value: object): value is MessageRead {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('messageType' in value) || value['messageType'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('replyToId' in value) || value['replyToId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MessageReadFromJSON(json: any): MessageRead {
    return MessageReadFromJSONTyped(json, false);
}

export function MessageReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRead {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'conversationId': json['conversation_id'],
        'senderId': json['sender_id'],
        'messageType': MessageTypeFromJSON(json['message_type']),
        'content': json['content'],
        'status': MessageStatusFromJSON(json['status']),
        'replyToId': json['reply_to_id'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function MessageReadToJSON(json: any): MessageRead {
    return MessageReadToJSONTyped(json, false);
}

export function MessageReadToJSONTyped(value?: MessageRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'conversation_id': value['conversationId'],
        'sender_id': value['senderId'],
        'message_type': MessageTypeToJSON(value['messageType']),
        'content': value['content'],
        'status': MessageStatusToJSON(value['status']),
        'reply_to_id': value['replyToId'],
        'created_at': value['createdAt'].toISOString(),
    };
}

