/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MessageStatus {
    Sent = 'sent',
    Delivered = 'delivered',
    Read = 'read',
    UnknownDefaultOpenApi = '11184809'
}


export function instanceOfMessageStatus(value: any): boolean {
    for (const key in MessageStatus) {
        if (Object.prototype.hasOwnProperty.call(MessageStatus, key)) {
            if (MessageStatus[key as keyof typeof MessageStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MessageStatusFromJSON(json: any): MessageStatus {
    return MessageStatusFromJSONTyped(json, false);
}

export function MessageStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageStatus {
    return json as MessageStatus;
}

export function MessageStatusToJSON(value?: MessageStatus | null): any {
    return value as any;
}

export function MessageStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): MessageStatus {
    return value as MessageStatus;
}

