/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageRead } from './MessageRead';
import {
    MessageReadFromJSON,
    MessageReadFromJSONTyped,
    MessageReadToJSON,
    MessageReadToJSONTyped,
} from './MessageRead';

/**
 * 
 * @export
 * @interface PaginatedMessages
 */
export interface PaginatedMessages {
    /**
     * 
     * @type {Array<MessageRead>}
     * @memberof PaginatedMessages
     */
    items: Array<MessageRead>;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMessages
     */
    nextCursor: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedMessages
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PaginatedMessages interface.
 */
export function instanceOfPaginatedMessages(value: object): value is PaginatedMessages {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function PaginatedMessagesFromJSON(json: any): PaginatedMessages {
    return PaginatedMessagesFromJSONTyped(json, false);
}

export function PaginatedMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMessages {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MessageReadFromJSON)),
        'nextCursor': json['next_cursor'],
        'hasMore': json['has_more'],
    };
}

export function PaginatedMessagesToJSON(json: any): PaginatedMessages {
    return PaginatedMessagesToJSONTyped(json, false);
}

export function PaginatedMessagesToJSONTyped(value?: PaginatedMessages | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MessageReadToJSON)),
        'next_cursor': value['nextCursor'],
        'has_more': value['hasMore'],
    };
}

