/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParticipantRole } from './ParticipantRole';
import {
    ParticipantRoleFromJSON,
    ParticipantRoleFromJSONTyped,
    ParticipantRoleToJSON,
    ParticipantRoleToJSONTyped,
} from './ParticipantRole';

/**
 * 
 * @export
 * @interface ParticipantRead
 */
export interface ParticipantRead {
    /**
     * 
     * @type {string}
     * @memberof ParticipantRead
     */
    userId: string;
    /**
     * 
     * @type {ParticipantRole}
     * @memberof ParticipantRead
     */
    role: ParticipantRole;
    /**
     * 
     * @type {number}
     * @memberof ParticipantRead
     */
    unreadCount: number;
    /**
     * 
     * @type {Date}
     * @memberof ParticipantRead
     */
    joinedAt: Date;
}



/**
 * Check if a given object implements the ParticipantRead interface.
 */
export function instanceOfParticipantRead(value: object): value is ParticipantRead {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function ParticipantReadFromJSON(json: any): ParticipantRead {
    return ParticipantReadFromJSONTyped(json, false);
}

export function ParticipantReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantRead {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'role': ParticipantRoleFromJSON(json['role']),
        'unreadCount': json['unread_count'],
        'joinedAt': (new Date(json['joined_at'])),
    };
}

export function ParticipantReadToJSON(json: any): ParticipantRead {
    return ParticipantReadToJSONTyped(json, false);
}

export function ParticipantReadToJSONTyped(value?: ParticipantRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'role': ParticipantRoleToJSON(value['role']),
        'unread_count': value['unreadCount'],
        'joined_at': value['joinedAt'].toISOString(),
    };
}

