/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ParticipantRole {
    Admin = 'admin',
    Member = 'member',
    UnknownDefaultOpenApi = '11184809'
}


export function instanceOfParticipantRole(value: any): boolean {
    for (const key in ParticipantRole) {
        if (Object.prototype.hasOwnProperty.call(ParticipantRole, key)) {
            if (ParticipantRole[key as keyof typeof ParticipantRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ParticipantRoleFromJSON(json: any): ParticipantRole {
    return ParticipantRoleFromJSONTyped(json, false);
}

export function ParticipantRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantRole {
    return json as ParticipantRole;
}

export function ParticipantRoleToJSON(value?: ParticipantRole | null): any {
    return value as any;
}

export function ParticipantRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): ParticipantRole {
    return value as ParticipantRole;
}

