/* tslint:disable */
/* eslint-disable */
/**
 * BiAnlat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    replyToId?: string | null;
}

/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): value is SendMessageRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'replyToId': json['reply_to_id'] == null ? undefined : json['reply_to_id'],
    };
}

export function SendMessageRequestToJSON(json: any): SendMessageRequest {
    return SendMessageRequestToJSONTyped(json, false);
}

export function SendMessageRequestToJSONTyped(value?: SendMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'reply_to_id': value['replyToId'],
    };
}

