/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRead
 */
export interface UserRead {
    /**
     * 
     * @type {string}
     * @memberof UserRead
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserRead
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRead
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRead
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserRead
     */
    phone: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserRead
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserRead
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserRead
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UserRead interface.
 */
export function instanceOfUserRead(value: object): value is UserRead {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserReadFromJSON(json: any): UserRead {
    return UserReadFromJSONTyped(json, false);
}

export function UserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRead {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'id': json['id'],
        'phone': json['phone'],
        'isActive': json['is_active'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UserReadToJSON(json: any): UserRead {
    return UserReadToJSONTyped(json, false);
}

export function UserReadToJSONTyped(value?: UserRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'bio': value['bio'],
        'id': value['id'],
        'phone': value['phone'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

