/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRequest
 */
export interface VerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyRequest
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyRequest interface.
 */
export function instanceOfVerifyRequest(value: object): value is VerifyRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyRequestFromJSON(json: any): VerifyRequest {
    return VerifyRequestFromJSONTyped(json, false);
}

export function VerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'code': json['code'],
    };
}

export function VerifyRequestToJSON(json: any): VerifyRequest {
    return VerifyRequestToJSONTyped(json, false);
}

export function VerifyRequestToJSONTyped(value?: VerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'code': value['code'],
    };
}

