/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeviceTokenDelete } from '../models';
// @ts-ignore
import type { DeviceTokenRegister } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Device Token
         * @param {DeviceTokenDelete} deviceTokenDelete 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDeviceTokenApiV1NotificationsDeviceTokensDelete: async (deviceTokenDelete: DeviceTokenDelete, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceTokenDelete' is not null or undefined
            assertParamExists('deleteDeviceTokenApiV1NotificationsDeviceTokensDelete', 'deviceTokenDelete', deviceTokenDelete)
            const localVarPath = `/api/v1/notifications/device-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceTokenDelete, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register Device Token
         * @param {DeviceTokenRegister} deviceTokenRegister 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerDeviceTokenApiV1NotificationsDeviceTokensPost: async (deviceTokenRegister: DeviceTokenRegister, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceTokenRegister' is not null or undefined
            assertParamExists('registerDeviceTokenApiV1NotificationsDeviceTokensPost', 'deviceTokenRegister', deviceTokenRegister)
            const localVarPath = `/api/v1/notifications/device-tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceTokenRegister, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete Device Token
         * @param {DeviceTokenDelete} deviceTokenDelete 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDeviceTokenApiV1NotificationsDeviceTokensDelete(deviceTokenDelete: DeviceTokenDelete, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDeviceTokenApiV1NotificationsDeviceTokensDelete(deviceTokenDelete, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.deleteDeviceTokenApiV1NotificationsDeviceTokensDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register Device Token
         * @param {DeviceTokenRegister} deviceTokenRegister 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerDeviceTokenApiV1NotificationsDeviceTokensPost(deviceTokenRegister: DeviceTokenRegister, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerDeviceTokenApiV1NotificationsDeviceTokensPost(deviceTokenRegister, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.registerDeviceTokenApiV1NotificationsDeviceTokensPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete Device Token
         * @param {DeviceTokenDelete} deviceTokenDelete 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDeviceTokenApiV1NotificationsDeviceTokensDelete(deviceTokenDelete: DeviceTokenDelete, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteDeviceTokenApiV1NotificationsDeviceTokensDelete(deviceTokenDelete, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register Device Token
         * @param {DeviceTokenRegister} deviceTokenRegister 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerDeviceTokenApiV1NotificationsDeviceTokensPost(deviceTokenRegister: DeviceTokenRegister, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.registerDeviceTokenApiV1NotificationsDeviceTokensPost(deviceTokenRegister, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi extends BaseAPI {
    /**
     * 
     * @summary Delete Device Token
     * @param {DeviceTokenDelete} deviceTokenDelete 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDeviceTokenApiV1NotificationsDeviceTokensDelete(deviceTokenDelete: DeviceTokenDelete, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).deleteDeviceTokenApiV1NotificationsDeviceTokensDelete(deviceTokenDelete, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register Device Token
     * @param {DeviceTokenRegister} deviceTokenRegister 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerDeviceTokenApiV1NotificationsDeviceTokensPost(deviceTokenRegister: DeviceTokenRegister, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).registerDeviceTokenApiV1NotificationsDeviceTokensPost(deviceTokenRegister, options).then((request) => request(this.axios, this.basePath));
    }
}

