/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ContactAddResult } from '../models';
// @ts-ignore
import type { ContactCreate } from '../models';
// @ts-ignore
import type { ContactRead } from '../models';
// @ts-ignore
import type { ContactUpdate } from '../models';
// @ts-ignore
import type { CursorPageContactRead } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { UserRead } from '../models';
// @ts-ignore
import type { UserUpdate } from '../models';
/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add Contact
         * @param {ContactCreate} contactCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addContactApiV1UsersContactsPost: async (contactCreate: ContactCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCreate' is not null or undefined
            assertParamExists('addContactApiV1UsersContactsPost', 'contactCreate', contactCreate)
            const localVarPath = `/api/v1/users/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Contact
         * @param {string} contactUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContactApiV1UsersContactsContactUserIdGet: async (contactUserId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactUserId' is not null or undefined
            assertParamExists('getContactApiV1UsersContactsContactUserIdGet', 'contactUserId', contactUserId)
            const localVarPath = `/api/v1/users/contacts/{contact_user_id}`
                .replace(`{${"contact_user_id"}}`, encodeURIComponent(String(contactUserId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMeApiV1UsersMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Contacts
         * @param {string | null} [q] 
         * @param {ListContactsApiV1UsersContactsGetStatusEnum} [status] 
         * @param {string | null} [cursor] Cursor for the next page
         * @param {number} [size] Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listContactsApiV1UsersContactsGet: async (q?: string | null, status?: ListContactsApiV1UsersContactsGetStatusEnum, cursor?: string | null, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove Contact
         * @param {string} contactId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeContactApiV1UsersContactsContactIdDelete: async (contactId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactId' is not null or undefined
            assertParamExists('removeContactApiV1UsersContactsContactIdDelete', 'contactId', contactId)
            const localVarPath = `/api/v1/users/contacts/{contact_id}`
                .replace(`{${"contact_id"}}`, encodeURIComponent(String(contactId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Contact
         * @param {string} contactId 
         * @param {ContactUpdate} contactUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateContactApiV1UsersContactsContactIdPatch: async (contactId: string, contactUpdate: ContactUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactId' is not null or undefined
            assertParamExists('updateContactApiV1UsersContactsContactIdPatch', 'contactId', contactId)
            // verify required parameter 'contactUpdate' is not null or undefined
            assertParamExists('updateContactApiV1UsersContactsContactIdPatch', 'contactUpdate', contactUpdate)
            const localVarPath = `/api/v1/users/contacts/{contact_id}`
                .replace(`{${"contact_id"}}`, encodeURIComponent(String(contactId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Me
         * @param {UserUpdate} userUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMeApiV1UsersMePatch: async (userUpdate: UserUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userUpdate' is not null or undefined
            assertParamExists('updateMeApiV1UsersMePatch', 'userUpdate', userUpdate)
            const localVarPath = `/api/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add Contact
         * @param {ContactCreate} contactCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addContactApiV1UsersContactsPost(contactCreate: ContactCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactAddResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addContactApiV1UsersContactsPost(contactCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.addContactApiV1UsersContactsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Contact
         * @param {string} contactUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContactApiV1UsersContactsContactUserIdGet(contactUserId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContactApiV1UsersContactsContactUserIdGet(contactUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getContactApiV1UsersContactsContactUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMeApiV1UsersMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMeApiV1UsersMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMeApiV1UsersMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Contacts
         * @param {string | null} [q] 
         * @param {ListContactsApiV1UsersContactsGetStatusEnum} [status] 
         * @param {string | null} [cursor] Cursor for the next page
         * @param {number} [size] Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listContactsApiV1UsersContactsGet(q?: string | null, status?: ListContactsApiV1UsersContactsGetStatusEnum, cursor?: string | null, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CursorPageContactRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listContactsApiV1UsersContactsGet(q, status, cursor, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.listContactsApiV1UsersContactsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove Contact
         * @param {string} contactId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeContactApiV1UsersContactsContactIdDelete(contactId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeContactApiV1UsersContactsContactIdDelete(contactId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.removeContactApiV1UsersContactsContactIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Contact
         * @param {string} contactId 
         * @param {ContactUpdate} contactUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateContactApiV1UsersContactsContactIdPatch(contactId: string, contactUpdate: ContactUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateContactApiV1UsersContactsContactIdPatch(contactId, contactUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateContactApiV1UsersContactsContactIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Me
         * @param {UserUpdate} userUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMeApiV1UsersMePatch(userUpdate: UserUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMeApiV1UsersMePatch(userUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateMeApiV1UsersMePatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary Add Contact
         * @param {ContactCreate} contactCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addContactApiV1UsersContactsPost(contactCreate: ContactCreate, options?: RawAxiosRequestConfig): AxiosPromise<ContactAddResult> {
            return localVarFp.addContactApiV1UsersContactsPost(contactCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Contact
         * @param {string} contactUserId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContactApiV1UsersContactsContactUserIdGet(contactUserId: string, options?: RawAxiosRequestConfig): AxiosPromise<ContactRead> {
            return localVarFp.getContactApiV1UsersContactsContactUserIdGet(contactUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMeApiV1UsersMeGet(options?: RawAxiosRequestConfig): AxiosPromise<UserRead> {
            return localVarFp.getMeApiV1UsersMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Contacts
         * @param {string | null} [q] 
         * @param {ListContactsApiV1UsersContactsGetStatusEnum} [status] 
         * @param {string | null} [cursor] Cursor for the next page
         * @param {number} [size] Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listContactsApiV1UsersContactsGet(q?: string | null, status?: ListContactsApiV1UsersContactsGetStatusEnum, cursor?: string | null, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<CursorPageContactRead> {
            return localVarFp.listContactsApiV1UsersContactsGet(q, status, cursor, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove Contact
         * @param {string} contactId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeContactApiV1UsersContactsContactIdDelete(contactId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeContactApiV1UsersContactsContactIdDelete(contactId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Contact
         * @param {string} contactId 
         * @param {ContactUpdate} contactUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateContactApiV1UsersContactsContactIdPatch(contactId: string, contactUpdate: ContactUpdate, options?: RawAxiosRequestConfig): AxiosPromise<ContactRead> {
            return localVarFp.updateContactApiV1UsersContactsContactIdPatch(contactId, contactUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Me
         * @param {UserUpdate} userUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMeApiV1UsersMePatch(userUpdate: UserUpdate, options?: RawAxiosRequestConfig): AxiosPromise<UserRead> {
            return localVarFp.updateMeApiV1UsersMePatch(userUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Add Contact
     * @param {ContactCreate} contactCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addContactApiV1UsersContactsPost(contactCreate: ContactCreate, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).addContactApiV1UsersContactsPost(contactCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Contact
     * @param {string} contactUserId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getContactApiV1UsersContactsContactUserIdGet(contactUserId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getContactApiV1UsersContactsContactUserIdGet(contactUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMeApiV1UsersMeGet(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMeApiV1UsersMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Contacts
     * @param {string | null} [q] 
     * @param {ListContactsApiV1UsersContactsGetStatusEnum} [status] 
     * @param {string | null} [cursor] Cursor for the next page
     * @param {number} [size] Page size
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listContactsApiV1UsersContactsGet(q?: string | null, status?: ListContactsApiV1UsersContactsGetStatusEnum, cursor?: string | null, size?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).listContactsApiV1UsersContactsGet(q, status, cursor, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove Contact
     * @param {string} contactId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeContactApiV1UsersContactsContactIdDelete(contactId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).removeContactApiV1UsersContactsContactIdDelete(contactId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Contact
     * @param {string} contactId 
     * @param {ContactUpdate} contactUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateContactApiV1UsersContactsContactIdPatch(contactId: string, contactUpdate: ContactUpdate, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateContactApiV1UsersContactsContactIdPatch(contactId, contactUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Me
     * @param {UserUpdate} userUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateMeApiV1UsersMePatch(userUpdate: UserUpdate, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateMeApiV1UsersMePatch(userUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}

export enum ListContactsApiV1UsersContactsGetStatusEnum {
    PendingRegistration = 'pending_registration',
    UnknownDefaultOpenApi = '11184809'
}
