/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Hem aktif (kayıtlı) hem de pending (kayıtsız) kişileri temsil eder.  id      → her zaman UserContact.id (PATCH/DELETE /contacts/{id} için kullanılır) user_id → sadece aktif contact\'larda User UUID\'si (sohbet başlatmak için); pending\'de None first_name is None → kişi henüz uygulamaya kayıt olmamış (pending)
 */
export interface ContactRead {
    'id': string;
    'user_id'?: string | null;
    'phone': string;
    'first_name'?: string | null;
    'last_name'?: string | null;
    'bio'?: string | null;
    'is_active'?: boolean;
    'created_at': string;
    'updated_at'?: string | null;
}

