/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConversationType } from './conversation-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LastMessageRead } from './last-message-read';
// May contain unused imports in some cases
// @ts-ignore
import type { ParticipantRead } from './participant-read';

export interface ConversationRead {
    'id': string;
    'type': ConversationType;
    'name': string | null;
    'avatar': string | null;
    'participants': Array<ParticipantRead>;
    'last_message': LastMessageRead | null;
    'unread_count': number;
    'created_at': string;
    'updated_at': string;
}



