/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConversationRead } from './conversation-read';

export interface CursorPageConversationRead {
    'items': Array<ConversationRead>;
    'total': number;
    'current_page'?: string | null;
    'current_page_backwards'?: string | null;
    'previous_page'?: string | null;
    'next_page'?: string | null;
}

