/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactRead } from './contact-read';

export interface CursorPageContactRead {
    'items': Array<ContactRead>;
    'total': number;
    'current_page'?: string | null;
    'current_page_backwards'?: string | null;
    'previous_page'?: string | null;
    'next_page'?: string | null;
}

