/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageStatus } from './message-status';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageType } from './message-type';

export interface MessageRead {
    'id': string;
    'conversation_id': string;
    'sender_id': string;
    'message_type': MessageType;
    'content': string;
    'status': MessageStatus;
    'reply_to_id': string | null;
    'created_at': string;
}



