/* tslint:disable */
/* eslint-disable */
/**
 * bianlat-be
 * BiAnlat Backend Application
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserRead {
    'first_name': string;
    'last_name'?: string | null;
    'bio'?: string | null;
    'id': string;
    'phone': string;
    'is_active': boolean;
    'created_at': string;
    'updated_at': string;
}

